### ISSUE TITLE
leetcode Memory Limit Exceeded 

### ISSUE THREAD

**Issue by qqli1209** [duteng/leetcode#1]
Hello, recently I have been written some code in Leetcode and I meet this problem and find your code. Here is the problem: No. 447 Number of Boomerangs. I use your code in this repository and test in leetcode but the results turn out to be "Memory Limit Exceeded" of the longest test array. Have you test your code in leetcode? Is this a problem with js or just the leetcode platform? Thank you very much!

**Comment by ravhb** [comment]
HI, @qqli1209 , I also have the same issue as you met.
We need analyze memory usage of the code by using the Chrome-Dev or Node.
I think the most probably reason is the code creating so many _map_ object.
